### ISSUE TITLE
Game does not properly assign player to team base specifically when the enter button is pressed on main menu on consecutive main menu enters.

### ISSUE THREAD

**Issue by o-chib** [o-chib/hexisle.io#134]
Steps to recreate:
1. Enter Main Menu
2. Press Enter (Red character spawns on red base)
3. Quit game, renter main menu
4. Press Enter Again (Blue player on red base or vice versa)

You can repeat steps 3 and 4 but the player color will not match the base it spawns on. This issue does not occur if you manually press the Play button.

**Comment by adunn27** [comment]
Fix added to #133
